# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11da7a40aa8a0b760ab5c93080889a3d98644b95f9d2ad4bf5acf4e57adb8d3f2e99e2c26f90fc69dee199c51974d8dfcf64f1624b53eb35a682392f54ea32d4

test:
  secret_key_base: 4224bd4780ef8603b3059bd6cd5ff9ba452d8e87bd9ade3f45f9018fcbc5f86cc7a09515bc897b4be3c5a467357827ff3545ce352eba067e2654d32e390de734

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
